from http.server import BaseHTTPRequestHandler

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        html = """<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>TITAN V32 FORCE BUY</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-[#0f172a] text-white p-3">
<div class="max-w-md mx-auto">
<h1 class="text-center font-bold text-sm tracking-widest">TITAN V32 FORCE BUY - TP/SL + BUY</h1>
<div class="text-center text-7xl font-black text-emerald-400 my-2" id="lastDigit">-</div>
<div class="text-center text-xs text-emerald-400" id="tickInfo">WAITING...</div>
<div class="grid grid-cols-5 gap-2 my-3" id="digitGrid"></div>
<div class="text-center text-xs">History:<span id="histCount">0</span> | PREDICT:<span id="predict">-</span> | CONF:<span id="conf">0</span>%</div>
<div class="text-center text-xs" id="hotCold"></div>
<div class="bg-slate-800 rounded-xl p-3 my-3 border border-emerald-500/30"><div id="scanStatus" class="text-emerald-400 font-bold text-sm">🧠 SCANNER: WAITING</div><div id="scanDetails" class="text-[11px] text-gray-300"></div><div id="bestMarket" class="text-xs mt-1 font-bold"></div></div>
<div class="text-center text-xs text-gray-400" id="dotStatus">🔴 DOT... NOT CONNECTED</div>
<div class="bg-slate-800 rounded-xl p-2 my-3 h-6 overflow-hidden text-[10px] text-gray-500" id="dotBox">..............................</div>
<button onclick="toggleToken()" class="w-full bg-emerald-500 text-black font-bold py-3 rounded-xl mb-3">👁️ Show / Hide Token</button>
<div class="grid grid-cols-2 gap-2 mb-2"><input id="stake" value="1" class="bg-slate-800 p-3 rounded-xl text-center"><input id="martingale" value="2.1" class="bg-slate-800 p-3 rounded-xl text-center"><input id="tp" value="10" class="bg-slate-800 p-3 rounded-xl text-center border border-emerald-500"><input id="sl" value="20" class="bg-slate-800 p-3 rounded-xl text-center border border-red-500"></div>
<div class="text-[11px] text-center text-gray-400 mb-2">TP = Take Profit (stop P >= TP) | SL = Stop Loss (stop P <= -SL)</div>
<div class="border border-gray-400 rounded-xl p-3 text-center mb-3"><input id="token" type="password" placeholder="Paste Deriv API Token" class="bg-transparent w-full text-center text-xs outline-none"><div id="tokenCheck" class="text-xs mt-1"></div></div>
<button onclick="startTrading()" class="w-full bg-gradient-to-r from-emerald-400 to-cyan-400 text-black font-black py-4 rounded-xl mb-2">🧠 ONE BUTTON SMART SCAN & TRADE</button>
<div class="grid grid-cols-2 gap-2"><button onclick="stopTrading()" class="bg-red-500 font-bold py-3 rounded-xl">⏹️ STOP</button><button onclick="clearLog()" class="bg-slate-800 font-bold py-3 rounded-xl">🧹 CLEAR</button></div>
<div class="text-center text-sm mt-3"><span id="balance">Bal:$0</span> | <span id="profit">P:$0.00</span> <span id="wins">W:0</span> <span id="loss">L:0</span> <span id="nextStake">Next:$1</span> | <span id="tradeStatus">HOLD</span></div>
<div class="text-center text-xs text-yellow-400" id="tpSlInfo">TP:$10 SL:$20 | 0% to TP | P:$0.00</div>
<div id="log" class="bg-black/50 rounded-xl p-2 mt-3 h-64 overflow-y-auto text-[11px] font-mono"></div>
</div>
<script>
let history=[],counts=Array(10).fill(0),ws=null,lastDigit=null,trading=false,nextStake=1,profit=0,wins=0,losses=0,token="",balance=0,dotConnected=false,awaitingResult=false;
const grid=document.getElementById("digitGrid"); for(let i=0;i<10;i++){let d=document.createElement("div"); d.className="bg-slate-800 rounded-xl p-2 text-center"; d.innerHTML=`<div class="font-bold">${i}</div><div class="text-[10px] text-gray-400" id="pct${i}">0%</div>`; d.id=`digit${i}`; grid.appendChild(d);}
function logM(m){let l=document.getElementById("log"); l.innerHTML+=`> ${m}<br>`; l.scrollTop=l.scrollHeight;}
function updateGrid(){let total=history.length||1; for(let i=0;i<10;i++){let p=Math.round(counts[i]/total*100); document.getElementById(`pct${i}`).innerText=p+"%"; document.getElementById(`digit${i}`).className=lastDigit==i?"bg-emerald-500/30 border border-emerald-400 rounded-xl p-2 text-center":"bg-slate-800 rounded-xl p-2 text-center";}}
function runScanner(){if(history.length<20){document.getElementById("scanStatus").innerText=`COLLECTING ${history.length}/20`; return null;} let total=history.length; let even=history.filter(d=>d%2==0).length; let evenPct=Math.round(even/total*100); let oddPct=100-evenPct; let over4=history.filter(d=>d>4).length; let overPct=Math.round(over4/total*100); let underPct=100-overPct; let over2=history.filter(d=>d>2).length; let over2Pct=Math.round(over2/total*100); let sorted=[...Array(10).keys()].map(i=>({d:i,c:counts[i],p:Math.round(counts[i]/total*100)})).sort((a,b)=>b.c-a.c); let top=sorted[0]; document.getElementById("scanDetails").innerText=`Even:${evenPct}% Odd:${oddPct}% | Over4:${overPct}% Under4:${underPct}% | Over2:${over2Pct}% | Top:${top.d} ${top.p}%`; document.getElementById("hotCold").innerHTML=`🔥 HOT:${sorted.slice(0,3).map(s=>s.d).join(" ")} ❄️ COLD:${sorted.slice(-3).map(s=>s.d).join(" ")}`; let opps=[]; if(evenPct>=65) opps.push({market:"DIGITEVEN",conf:evenPct,type:`Even ${evenPct}%`,barrier:null}); if(oddPct>=65) opps.push({market:"DIGITODD",conf:oddPct,type:`Odd ${oddPct}%`,barrier:null}); if(overPct>=65) opps.push({market:"DIGITOVER",barrier:4,conf:overPct,type:`Over4 ${overPct}%`}); if(underPct>=65) opps.push({market:"DIGITUNDER",barrier:4,conf:underPct,type:`Under4 ${underPct}%`}); if(over2Pct>=76) opps.push({market:"DIGITOVER",barrier:2,conf:over2Pct,type:`Over2 ${over2Pct}%`}); if((100-over2Pct)>=76) opps.push({market:"DIGITUNDER",barrier:2,conf:100-over2Pct,type:`Under2 ${100-over2Pct}%`}); if(top.p>=28) opps.push({market:"DIGITMATCH",barrier:top.d,conf:top.p+40,type:`Match ${top.d} ${top.p}%`}); opps.sort((a,b)=>b.conf-a.conf); let best=opps[0]; if(best){document.getElementById("scanStatus").innerText=`✅ FAVOURABLE FOUND`; document.getElementById("scanStatus").style.color="#2df28b"; document.getElementById("bestMarket").innerText=`🎯 ${best.type} → ${best.market} ${best.barrier??""} (${best.conf}%)`; return best;} else{document.getElementById("scanStatus").innerText=`⏸️ HOLDING - No 65%+ edge`; document.getElementById("scanStatus").style.color="#f59e0b"; document.getElementById("bestMarket").innerText=`HOLD - Waiting edge`; return null;}}
function connectTicks(){if(ws) ws.close(); ws=new WebSocket("wss://ws.derivws.com/websockets/v3?app_id=1089"); ws.onopen=()=>{ws.send(JSON.stringify({ticks:"R_10"})); logM(`TICK FEED CONNECTED R_10`);}; ws.onmessage=(e)=>{let data=JSON.parse(e.data); if(data.tick){let d=Number(String(data.tick.quote).slice(-1)); lastDigit=d; history.push(d); if(history.length>100) counts[history.shift()]--; counts[d]++; if(history.length>100) history.shift(); document.getElementById("lastDigit").innerText=d; document.getElementById("tickInfo").innerText=`TICK ${data.tick.quote} LAST:${d} via R_10`; document.getElementById("histCount").innerText=history.length; updateGrid(); let best=runScanner(); if(best){logM(`TICK ${data.tick.quote} LAST:${d} | ✅ FAVOURABLE FOUND`); if(trading &&!awaitingResult) doTrade(best);} else{logM(`TICK ${data.tick.quote} LAST:${d} | ⏸️ HOLDING`);} } if(data.msg_type=="authorize"){balance=data.authorize.balance; document.getElementById("balance").innerText=`Bal:$${balance.toFixed(2)}`; dotConnected=true; document.getElementById("dotStatus").innerText=`🟢 ${token.slice(0,10)} CONNECTED`; document.getElementById("tokenCheck").innerText=`✅ ${token.slice(0,10)}`; document.getElementById("dotBox").innerText=data.authorize.logininfo?data.authorize.logininfo.email:"CONNECTED"; logM(`🔐 AUTH OK Bal $${balance}`);} if(data.msg_type=="proposal_open_contract"){if(data.proposal_open_contract.is_sold){let p=Number(data.proposal_open_contract.profit); profit+=p; if(p>0) wins++; else losses++; if(p>0){nextStake=Number(document.getElementById("stake").value);} else{nextStake=nextStake*Number(document.getElementById("martingale").value);} document.getElementById("profit").innerText=`P:$${profit.toFixed(2)}`; document.getElementById("wins").innerText=`W:${wins}`; document.getElementById("loss").innerText=`L:${losses}`; document.getElementById("nextStake").innerText=`Next:$${nextStake.toFixed(2)}`; document.getElementById("tpSlInfo").innerText=`TP:$${document.getElementById("tp").value} SL:$${document.getElementById("sl").value} | ${Math.round(profit/Number(document.getElementById("tp").value)*100)}% to TP | P:$${profit.toFixed(2)}`; balance=data.proposal_open_contract.balance_after||balance; document.getElementById("balance").innerText=`Bal:$${balance.toFixed(2)}`; if(p>0) logM(`✅ WIN $${p.toFixed(2)} P:$${profit.toFixed(2)} W:${wins}`); else logM(`❌ LOSS $${p.toFixed(2)} P:$${profit.toFixed(2)} L:${losses}`); awaitingResult=false; document.getElementById("tradeStatus").innerText="HOLD"; if(profit>=Number(document.getElementById("tp").value)){logM(`🎯 TP HIT $${profit} STOPPING`); trading=false;} if(profit<=-Number(document.getElementById("sl").value)){logM(`🛑 SL HIT $${profit} STOPPING`); trading=false;}} } if(data.error){logM(`❌ ERR ${data.error.message}`); awaitingResult=false;}}; ws.onerror=()=>logM(`❌ WS ERROR`);}
function authorize(){token=document.getElementById("token").value.trim(); if(!token){logM(`❌ NO TOKEN`); return;} if(!ws) connectTicks(); setTimeout(()=>{ws.send(JSON.stringify({authorize:token}));},500);}
function doTrade(best){if(!dotConnected){logM(`❌ NOT CONNECTED`); return;} if(awaitingResult){return;} let stake=nextStake; let req={proposal:1, amount:stake, basis:"stake", contract_type:best.market, currency:"USD", symbol:"R_10", duration:1, duration_unit:"t"}; if(best.barrier!==null && best.barrier!==undefined) req.barrier=best.barrier; if(best.market==="DIGITOVER"||best.market==="DIGITUNDER") req.barrier=best.barrier; if(best.market==="DIGITMATCH"||best.market==="DIGITDIFF") req.barrier=best.barrier; logM(`🎯 TRADE → ${best.type} ${best.market} ${best.barrier??""} $${stake} CONF:${best.conf}%`); ws.send(JSON.stringify(req)); let propHandler=(ev)=>{let d=JSON.parse(ev.data); if(d.msg_type=="proposal"){let id=d.proposal.id; let ask=d.proposal.ask_price; logM(`PROP ${id.slice(0,6)} $${ask} → BUYING`); ws.send(JSON.stringify({buy:id, price:ask}));} if(d.msg_type=="buy"){if(d.buy){logM(`📈 BOUGHT ${d.buy.contract_id} $${d.buy.buy_price} CONFIRMED`); awaitingResult=true; document.getElementById("tradeStatus").innerText="TRADING"; ws.send(JSON.stringify({proposal_open_contract:1, contract_id:d.buy.contract_id, subscribe:1}));} if(d.error){logM(`❌ BUY ERR ${d.error.message}`); awaitingResult=false;}}}; ws.addEventListener("message",propHandler,{once:false}); setTimeout(()=>{ws.removeEventListener("message",propHandler);},5000);}
function startTrading(){token=document.getElementById("token").value.trim(); if(!token){logM(`❌ PASTE TOKEN FIRST`); return;} if(!dotConnected) authorize(); trading=true; logM(`🧠 SMART SCAN & TRADE STARTED Stake $${document.getElementById("stake").value}`); document.getElementById("tradeStatus").innerText="SCANNING";}
function stopTrading(){trading=false; awaitingResult=false; logM(`⏹️ STOPPED`); document.getElementById("tradeStatus").innerText="STOPPED";}
function clearLog(){document.getElementById("log").innerHTML="";} function toggleToken(){let t=document.getElementById("token"); t.type=t.type=="password"?"text":"password";}
document.getElementById("token").addEventListener("input",()=>{token=document.getElementById("token").value.trim(); localStorage.setItem("deriv_token",token); if(token) authorize();});
window.onload=()=>{let saved=localStorage.getItem("deriv_token"); if(saved){document.getElementById("token").value=saved; token=saved; } connectTicks(); if(saved) setTimeout(authorize,1000);};
</script></body></html>
"""
        self.wfile.write(html.encode())
