from http.server import BaseHTTPRequestHandler
class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type","text/html")
        self.end_headers()
        html="""<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>TITAN V33 CONNECT FIX</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-[#0f172a] text-white p-3">
<div class="max-w-md mx-auto">
<h1 class="text-center font-bold text-sm">TITAN V33 CONNECT FIX</h1>
<div class="text-center text-7xl font-black text-emerald-400 my-2" id="lastDigit">-</div>
<div class="text-center text-xs text-emerald-400" id="tickInfo">WAITING FOR CONNECT...</div>
<div class="grid grid-cols-5 gap-2 my-3" id="digitGrid"></div>
<div class="text-center text-xs">History:<span id="histCount">0</span> | CONF:<span id="conf">0</span>%</div>
<div class="bg-slate-800 rounded-xl p-3 my-3 border border-emerald-500/30"><div id="scanStatus" class="text-emerald-400 font-bold text-sm">🧠 SCANNER: WAITING</div><div id="scanDetails" class="text-[11px] text-gray-300"></div><div id="bestMarket" class="text-xs mt-1 font-bold"></div></div>
<div class="text-center text-xs" id="dotStatus">🔴 NOT CONNECTED - Paste token then tap CONNECT</div>
<div class="grid grid-cols-1 gap-2 mb-2">
<input id="token" type="password" placeholder="Paste Deriv API Token here (a1-...)" class="bg-slate-800 p-3 rounded-xl text-center text-xs">
<button onclick="connectNow()" class="w-full bg-blue-500 font-black py-3 rounded-xl">🔌 CONNECT NOW</button>
</div>
<button onclick="toggleToken()" class="w-full bg-emerald-500 text-black font-bold py-2 rounded-xl mb-3 text-sm">👁️ Show/Hide Token</button>
<div class="grid grid-cols-2 gap-2 mb-2"><input id="stake" value="1" class="bg-slate-800 p-3 rounded-xl text-center"><input id="martingale" value="2.1" class="bg-slate-800 p-3 rounded-xl text-center"><input id="tp" value="10" class="bg-slate-800 p-3 rounded-xl text-center border border-emerald-500"><input id="sl" value="20" class="bg-slate-800 p-3 rounded-xl text-center border border-red-500"></div>
<button onclick="startTrading()" class="w-full bg-gradient-to-r from-emerald-400 to-cyan-400 text-black font-black py-4 rounded-xl mb-2">🧠 ONE BUTTON SCAN & TRADE</button>
<div class="grid grid-cols-2 gap-2"><button onclick="stopTrading()" class="bg-red-500 font-bold py-3 rounded-xl">⏹️ STOP</button><button onclick="clearLog()" class="bg-slate-800 font-bold py-3 rounded-xl">🧹 CLEAR</button></div>
<div class="text-center text-sm mt-3"><span id="balance">Bal:$0</span> | <span id="profit">P:$0.00</span> <span id="wins">W:0</span> <span id="loss">L:0</span> <span id="nextStake">Next:$1</span> | <span id="tradeStatus">HOLD</span></div>
<div id="log" class="bg-black/50 rounded-xl p-2 mt-3 h-64 overflow-y-auto text-[11px] font-mono"></div>
</div>
<script>
let history=[],counts=Array(10).fill(0),ws=null,lastDigit=null,trading=false,nextStake=1,profit=0,wins=0,losses=0,token="",balance=0,dotConnected=false,awaitingResult=false;
const grid=document.getElementById("digitGrid"); for(let i=0;i<10;i++){let d=document.createElement("div"); d.className="bg-slate-800 rounded-xl p-2 text-center"; d.innerHTML=`<div class="font-bold">${i}</div><div class="text-[10px] text-gray-400" id="pct${i}">0%</div>`; grid.appendChild(d);}
function logM(m){let l=document.getElementById("log"); l.innerHTML+=`> ${m}<br>`; l.scrollTop=l.scrollHeight;}
function updateGrid(){let total=history.length||1; for(let i=0;i<10;i++){let p=Math.round(counts[i]/total*100); document.getElementById(`pct${i}`).innerText=p+"%";}}
function runScanner(){if(history.length<20){document.getElementById("scanStatus").innerText=`COLLECTING ${history.length}/20`; return null;} let total=history.length; let even=history.filter(d=>d%2==0).length; let evenPct=Math.round(even/total*100); let oddPct=100-evenPct; let over4=history.filter(d=>d>4).length; let overPct=Math.round(over4/total*100); let underPct=100-overPct; let over2=history.filter(d=>d>2).length; let over2Pct=Math.round(over2/total*100); let sorted=[...Array(10).keys()].map(i=>({d:i,c:counts[i],p:Math.round(counts[i]/total*100)})).sort((a,b)=>b.c-a.c); let top=sorted[0]; document.getElementById("scanDetails").innerText=`Even:${evenPct}% Odd:${oddPct}% | Over4:${overPct}% Under4:${underPct}% | Over2:${over2Pct}% | Top:${top.d} ${top.p}%`; let opps=[]; if(evenPct>=65) opps.push({market:"DIGITEVEN",conf:evenPct,type:`Even ${evenPct}%`,barrier:null}); if(oddPct>=65) opps.push({market:"DIGITODD",conf:oddPct,type:`Odd ${oddPct}%`,barrier:null}); if(overPct>=65) opps.push({market:"DIGITOVER",barrier:4,conf:overPct,type:`Over4 ${overPct}%`}); if(underPct>=65) opps.push({market:"DIGITUNDER",barrier:4,conf:underPct,type:`Under4 ${underPct}%`}); if(over2Pct>=76) opps.push({market:"DIGITOVER",barrier:2,conf:over2Pct,type:`Over2 ${over2Pct}%`}); if((100-over2Pct)>=76) opps.push({market:"DIGITUNDER",barrier:2,conf:100-over2Pct,type:`Under2 ${100-over2Pct}%`}); if(top.p>=28) opps.push({market:"DIGITMATCH",barrier:top.d,conf:top.p+40,type:`Match ${top.d} ${top.p}%`}); opps.sort((a,b)=>b.conf-a.conf); let best=opps[0]; if(best){document.getElementById("scanStatus").innerText=`✅ FAVOURABLE FOUND`; document.getElementById("bestMarket").innerText=`🎯 ${best.type} → ${best.market} ${best.barrier??""} (${best.conf}%)`; return best;} else{document.getElementById("scanStatus").innerText=`⏸️ HOLDING`; return null;}}
function connectTicks(){if(ws) ws.close(); ws=new WebSocket("wss://ws.derivws.com/websockets/v3?app_id=1089"); ws.onopen=()=>{ws.send(JSON.stringify({ticks:"R_10"})); logM(`TICK FEED CONNECTED R_10`);}; ws.onmessage=(e)=>{let data=JSON.parse(e.data); if(data.tick){let d=Number(String(data.tick.quote).slice(-1)); lastDigit=d; history.push(d); counts[d]++; if(history.length>100) history.shift(); document.getElementById("lastDigit").innerText=d; document.getElementById("tickInfo").innerText=`TICK ${data.tick.quote} LAST:${d}`; document.getElementById("histCount").innerText=history.length; updateGrid(); let best=runScanner(); if(best){ if(trading &&!awaitingResult) doTrade(best);}} if(data.msg_type=="authorize"){balance=data.authorize.balance; document.getElementById("balance").innerText=`Bal:$${balance.toFixed(2)}`; dotConnected=true; document.getElementById("dotStatus").innerText=`🟢 CONNECTED Bal:$${balance.toFixed(2)}`; document.getElementById("dotStatus").style.color="#22c55e"; logM(`🔐 AUTH OK Bal $${balance}`);} if(data.msg_type=="proposal_open_contract"&&data.proposal_open_contract.is_sold){let p=Number(data.proposal_open_contract.profit); profit+=p; if(p>0) wins++; else losses++; if(p>0) nextStake=Number(document.getElementById("stake").value); else nextStake=nextStake*Number(document.getElementById("martingale").value); document.getElementById("profit").innerText=`P:$${profit.toFixed(2)}`; document.getElementById("wins").innerText=`W:${wins}`; document.getElementById("loss").innerText=`L:${losses}`; document.getElementById("nextStake").innerText=`Next:$${nextStake.toFixed(2)}`; if(p>0) logM(`✅ WIN $${p.toFixed(2)} P:$${profit.toFixed(2)}`); else logM(`❌ LOSS $${p.toFixed(2)} P:$${profit.toFixed(2)}`); awaitingResult=false;} if(data.error){logM(`❌ ERR ${data.error.message}`); awaitingResult=false;}};}
function connectNow(){token=document.getElementById("token").value.trim(); if(!token){logM(`❌ PASTE TOKEN FIRST in the box above`); return;} localStorage.setItem("deriv_token",token); connectTicks(); setTimeout(()=>{ws.send(JSON.stringify({authorize:token}));},800); logM(`🔌 CONNECTING with ${token.slice(0,6)}...`);}
function doTrade(best){if(!dotConnected){logM(`❌ NOT CONNECTED - Tap CONNECT NOW first`); return;} if(awaitingResult) return; let stake=nextStake; let req={proposal:1,amount:stake,basis:"stake",contract_type:best.market,currency:"USD",symbol:"R_10",duration:1,duration_unit:"t"}; if(best.barrier!=null) req.barrier=best.barrier; logM(`🎯 TRADE → ${best.type} $${stake}`); ws.send(JSON.stringify(req)); let h=(ev)=>{let d=JSON.parse(ev.data); if(d.msg_type=="proposal"){ws.send(JSON.stringify({buy:d.proposal.id,price:d.proposal.ask_price})); logM(`PROP $${d.proposal.ask_price} → BUYING`);} if(d.msg_type=="buy"&&d.buy){logM(`📈 BOUGHT ${d.buy.contract_id} CONFIRMED`); awaitingResult=true; ws.send(JSON.stringify({proposal_open_contract:1,contract_id:d.buy.contract_id,subscribe:1}));}}; ws.addEventListener("message",h); setTimeout(()=>ws.removeEventListener("message",h),5000);}
function startTrading(){trading=true; logM(`🧠 SCAN & TRADE STARTED`); if(!dotConnected) connectNow();}
function stopTrading(){trading=false; logM(`⏹️ STOPPED`);} function clearLog(){document.getElementById("log").innerHTML="";} function toggleToken(){let t=document.getElementById("token"); t.type=t.type=="password"?"text":"password";}
window.onload=()=>{let s=localStorage.getItem("deriv_token"); if(s){document.getElementById("token").value=s;}}
</script></body></html>"""
        self.wfile.write(html.encode())
"""
        self.wfile.write(html.encode())
